package Lopt::Constants;

use Exporter qw(import);

our @EXPORT = qw(
    $NO_PROCESS_PID
    $PID_FILE_DELIMITER
    $NO_PROCESS_STATE
    $PROCESS_STOPPED_STATE
    $PROCESS_RUNNING_STATE
    $PROCESS_PAUSED_STATE
    $NO_RUNNING_PROCESS
    $TASK_LOGFILE_NAME
    $PID_FILE
    $TASK_EXECUTION_PARAMS_FILE
    $USER_HOME_FILE
    $REQUEST_MODEL_NOT_ACTUAL_KEYS
    $SHADOW_PATH
    $MONGO_URL
    $MONGO_DB_NAME
    $MONGO_TASKS_COLLECTION_NAME
    $MONGO_LAST_TASK_COLLECTION_NAME
);

our $NO_PROCESS_PID = -1;
our $PID_FILE_DELIMITER = ':';
our $NO_PROCESS_STATE = -1;
our $PROCESS_STOPPED_STATE = -1;
our $PROCESS_RUNNING_STATE = 0;
our $PROCESS_PAUSED_STATE = 1;
our $NO_RUNNING_PROCESS = join($PID_FILE_DELIMITER, ($NO_PROCESS_PID, $NO_PROCESS_STATE));

our $TASK_LOGFILE_NAME = 'task.log';
our $PID_FILE = 'running_task.pid';
our $TASK_EXECUTION_PARAMS_FILE = 'execution.json';
our $USER_HOME_FILE = '.created_by_task_executor';
our $REQUEST_MODEL_NOT_ACTUAL_KEYS = 'not_actual_keys';
our $SHADOW_PATH = '/etc/shadow';

our $MONGO_URL = 'mongodb://127.0.0.1:27017';
our $MONGO_DB_NAME = 'taskexecutor';
our $MONGO_TASKS_COLLECTION_NAME = 'tasks';
our $MONGO_LAST_TASK_COLLECTION_NAME = 'lasttasks';

1;
